#ifndef __API_CLIENT_TEST_SUITES_H__
#define __API_CLIENT_TEST_SUITES_H__

DECL_TESTSUITE_PER_BACKEND(login_test)

#define DEFINE_CLIENT_TESTSUITES \
    DEFINE_TESTSUITE_PER_BACKEND(login_test)

#endif /* __API_CLIENT_TEST_SUITES_H__ */
