#ifndef __API_FILE_TEST_SUITES_H__
#define __API_FILE_TEST_SUITES_H__

DECL_TESTSUITE_PER_BACKEND(dajf)

#define DEFINE_FILE_TESTSUITES \
    DEFINE_TESTSUITE_PER_BACKEND(dajf)

#endif /* __API_FILE_TEST_SUITES_H__ */
