#ifndef __API_DRIVE_TEST_SUITES_H__
#define __API_DRIVE_TEST_SUITES_H__

DECL_TESTSUITE_PER_BACKEND(drive_open_test)
DECL_TESTSUITE_PER_BACKEND(drive_get_info_test)
DECL_TESTSUITE_PER_BACKEND(list_files_test)
DECL_TESTSUITE_PER_BACKEND(file_ops_test)

#define DEFINE_DRIVE_TESTSUITES \
    DEFINE_TESTSUITE_PER_BACKEND(drive_open_test), \
    DEFINE_TESTSUITE_PER_BACKEND(drive_get_info_test), \
    DEFINE_TESTSUITE_PER_BACKEND(list_files_test), \
    DEFINE_TESTSUITE_PER_BACKEND(file_ops_test)

#endif /* __API_DRIVE_TEST_SUITES_H__ */
