#ifndef __API_DRIVE_TEST_SUITES_H__
#define __API_DRIVE_TEST_SUITES_H__

DECL_TESTSUITE_PER_BACKEND(abc)

#define DEFINE_DRIVE_TESTSUITES \
    DEFINE_TESTSUITE_PER_BACKEND(abc)

#endif /* __API_DRIVE_TEST_SUITES_H__ */
